### ISSUE TITLE
Provide atomic accesses to guest memory

### ISSUE THREAD

**Issue by alexandruag** [rust-vmm/vm-memory#16]
We should fix logic that handles guest memory access and does not guarantee the operations will have volatile semantics. One example is the `copy` here: https://github.com/rust-vmm/vm-memory/blob/08b24bf6245459f14226f52f19f91ad9648ad8e6/src/volatile_memory.rs#L277

**Comment by bonzini** [comment]
Hmm, this is not actually what I wanted to work on.  The issue is that the rust compiler (and the processor on weakly-ordered architectures) need to be told about possibly concurrent access, and they should be properly annotated as "atomic" rather than "volatile". My idea here is to add a VolatileAtomicRef struct similar to VolatileRef, but supporting atomic load and store instead of Deref and DerefMut.

**Comment by alexandruag** [comment]
Sorry about that :( For some reason I thought this one implies the other as well, but even if it did, the description was not clear at all in this regard. Assigned myself for this one.
