### ISSUE TITLE
Trait depending on implementations

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vm-memory#21]
I just got some more time to look to the vm-memory code. Should the memory regions and the guest memory traits depend on traits instead of actual implementations?
We have Address which is a trait and GuestAddress which implements the trait. Then when creating the memory region trait instead of using the address trait we are using the GuestAddress. Is this intended? If yes then what is the point of having Address as a trait? It looks like we are limited to using u64 addresses.

Pinging @bonzini & @jiangliu

**Comment by jiangliu** [comment]
When implement this the first time, we thought u64 should be enough and it also covers 32bit vms, so the concrete GuestAddress type is used instead of the Address trait. If the there are strong requirements for 32bit guests and it doesn't make the code too complex, it's Ok to use the Address trait:)
